_target_: src.models.DiffFlowModule.DiffFlowModule

net:
  _target_: src.models.components.DiffFlowCom.DiffFlow.DiffFlow
  data_shape:
    - 2

  timestamp:
    _target_: src.utils.DiffFlow.scalars.ExpTimer
    num_steps: 30
    t_start: 0.001
    t_end: 0.05
    exp: 0.9

  condition: ${model.net.timestamp}

  diffusion:
    _target_: src.utils.DiffFlow.scalars.ExpTimer
    num_steps: ${model.net.timestamp.num_steps}
    t_start: 0.2
    t_end: ${model.net.diffusion.t_start}


  score_net:
    _target_: src.models.components.DiffFlowCom.fouriermlp.FourierMLP
    data_shape: ${model.net.data_shape}
    num_layers: 3
    channels: 128

  drift_net: ${model.net.score_net}


#loss_fn: modules.sde_loss.loss_fn_wrapper
#trainer_register: modules.sde_ps_fns.points_trainer_register
