_target_: src.datamodules.gesture_datamodule.GestureDataModule
data_dir: ${paths.data_dir} # data_dir is specified in config.yaml
full_body_data_dir: ${paths.full_body_data_dir}
with_transcript_data_dir: ${paths.with_transcript_data_dir}
#data_dir: '/home/zf223669/Mount/DiffusionGestureGeneration/data/GesturesData'
framerate: 20
seqlen: 5
n_lookahead: 5
dropout: 0.2
batch_size: 50
#input_size: 972 # upper_body
#input_size: 927 # no x_n fps=20
#input_size: 927 #no transcript
input_size: 9025 # with transcript
#input_size: 1053 # full_body 65 joints
num_workers: 16
is_full_body: False
is_with_transcript: True
is_smoothing: True
window_length: 31 # 51 to0 large
polyorder: 4  # 2 too smooth,
#input_size: 1017
